In [ ]:
#filling :
1. Mode: categorical or ordinal data  -> Text 

2. Median:where outliers are too much

3. Mean: no outliers


#Can formatting be done in pandas -> heading extra bold,colored background,text highlight
#uploading and downloading
->sql
->json
->excel
->csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\bhard\Downloads\archive.zip")

In [3]:
df.head(20)

,User_ID,Product_ID,Category,Price (Rs.),Discount (%),Final_Price(Rs.),Payment_Method,Purchase_Date
0,337c166f,f414122f-e,Sports,36.53,15,31.05,Net Banking,12-11-2024
1,d38a19bf,fde50f9c-5,Clothing,232.79,20,186.23,Net Banking,09-02-2024
2,d7f5f0b0,0d96fc90-3,Sports,317.02,25,237.76,Credit Card,01-09-2024
3,395d4994,964fc44b-d,Toys,173.19,25,129.89,UPI,01-04-2024
4,a83c145c,d70e2fc6-e,Beauty,244.80,20,195.84,Net Banking,27-09-2024
5,3fdcdae8,0816ee12-5,Books,241.86,50,120.93,UPI,08-08-2024
6,12772337,d41e0b55-c,Toys,76.91,5,73.06,Credit Card,28-03-2024
7,9f0194af,83b7dc04-5,Sports,213.23,20,170.58,Net Banking,29-05-2024
8,7a8559d8,87c9c896-1,Sports,379.81,5,360.82,Credit Card,26-02-2024
9,8911f0d1,31308875-b,Home & Kitchen,415.36,50,207.68,Net Banking,11-01-2024
10,98857e41,b2b1af7b-7,Books,73.09,10,65.78,Cash on Delivery,21-10-2024
11,3b857e65,e221cf14-c,Beauty,393.77,15,334.70,Cash on Delivery,10-09-2024
12,204fab33,8c9a5f54-b,Home & Kitchen,287.69,10,258.92,Credit Card,08-03-2024
13,88159234,eeb0635d-a,Sports,26.26,50,13.13,Credit Card,10-05-2024
14,8c1f2f98,38aec303-2,Clothing,305.10,25,228.83,UPI,20-06-2024
15,a84d7206,69d91fbc-3,Home & Kitchen,113.71,5,108.02,Credit Card,28-04-2024
16,4578c08e,928b4b24-d,Toys,426.75,0,426.75,Net Banking,17-08-2024
17,ba3964fa,12f03ff4-6,Home & Kitchen,52.98,0,52.98,Net Banking,08-08-2024
18,78595586,729191af-4,Electronics,223.89,0,223.89,Cash on Delivery,13-06-2024
19,195e0c14,089c1cdd-0,Clothing,166.75,0,166.75,Debit Card,23-09-2024

In [4]:
df.tail()

,User_ID,Product_ID,Category,Price (Rs.),Discount (%),Final_Price(Rs.),Payment_Method,Purchase_Date
3655,67abda0a,28714133-6,Beauty,486.79,0,486.79,UPI,14-05-2024
3656,34ebc1a0,08838c2c-9,Toys,212.87,15,180.94,Cash on Delivery,19-11-2024
3657,1defd3b1,c39a4f16-6,Home & Kitchen,389.76,0,389.76,Net Banking,07-08-2024
3658,0611293d,b4f67f96-9,Electronics,447.66,30,313.36,UPI,21-05-2024
3659,e73ad07c,a5d07442-d,Home & Kitchen,235.77,30,165.04,UPI,14-04-2024

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3660 entries, 0 to 3659
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           3660 non-null   object
 1   Product_ID        3660 non-null   object
 2   Category          3660 non-null   object
 3   Price (Rs.)       3660 non-null   float64
 4   Discount (%)      3660 non-null   int64
 5   Final_Price(Rs.)  3660 non-null   float64
 6   Payment_Method    3660 non-null   object
 7   Purchase_Date     3660 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 228.9+ KB

In [7]:
df.describe()

       Price (Rs.)  Discount (%)  Final_Price(Rs.)
count  3660.000000   3660.000000       3660.000000
mean    254.800675     18.825137        206.906579
std     141.682621     14.731338        122.687844
min      10.090000      0.000000          5.890000
25%     134.012500      5.000000        104.512500
50%     253.845000     15.000000        199.185000
75%     377.595000     25.000000        304.117500
max     499.960000     50.000000        496.820000

In [9]:
df.isnull().sum()

User_ID             0
Product_ID          0
Category            0
Price (Rs.)         0
Discount (%)        0
Final_Price(Rs.)    0
Payment_Method      0
Purchase_Date       0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.columns

Index(['User_ID', 'Product_ID', 'Category', 'Price (Rs.)', 'Discount (%)',
       'Final_Price(Rs.)', 'Payment_Method', 'Purchase_Date'],
      dtype='object')

In [14]:
df["User_ID"]

0       337c166f
1       d38a19bf
2       d7f5f0b0
3       395d4994
4       a83c145c
          ...
3655    67abda0a
3656    34ebc1a0
3657    1defd3b1
3658    0611293d
3659    e73ad07c
Name: User_ID, Length: 3660, dtype: object

In [22]:
df["Price (Rs.)"]

0        36.53
1       232.79
2       317.02
3       173.19
4       244.80
         ...
3655    486.79
3656    212.87
3657    389.76
3658    447.66
3659    235.77
Name: Price (Rs.), Length: 3660, dtype: float64

In [21]:
#Extracting records 
df[df["Price (Rs.)"]>200]

,User_ID,Product_ID,Category,Price (Rs.),Discount (%),Final_Price(Rs.),Payment_Method,Purchase_Date
1,d38a19bf,fde50f9c-5,Clothing,232.79,20,186.23,Net Banking,09-02-2024
2,d7f5f0b0,0d96fc90-3,Sports,317.02,25,237.76,Credit Card,01-09-2024
4,a83c145c,d70e2fc6-e,Beauty,244.80,20,195.84,Net Banking,27-09-2024
5,3fdcdae8,0816ee12-5,Books,241.86,50,120.93,UPI,08-08-2024
7,9f0194af,83b7dc04-5,Sports,213.23,20,170.58,Net Banking,29-05-2024
...,...,...,...,...,...,...,...,...
3655,67abda0a,28714133-6,Beauty,486.79,0,486.79,UPI,14-05-2024
3656,34ebc1a0,08838c2c-9,Toys,212.87,15,180.94,Cash on Delivery,19-11-2024
3657,1defd3b1,c39a4f16-6,Home & Kitchen,389.76,0,389.76,Net Banking,07-08-2024
3658,0611293d,b4f67f96-9,Electronics,447.66,30,313.36,UPI,21-05-2024
3659,e73ad07c,a5d07442-d,Home & Kitchen,235.77,30,165.04,UPI,14-04-2024

In [25]:
df.drop_duplicates().reset_index(drop="TRUE")

,User_ID,Product_ID,Category,Price (Rs.),Discount (%),Final_Price(Rs.),Payment_Method,Purchase_Date
0,337c166f,f414122f-e,Sports,36.53,15,31.05,Net Banking,12-11-2024
1,d38a19bf,fde50f9c-5,Clothing,232.79,20,186.23,Net Banking,09-02-2024
2,d7f5f0b0,0d96fc90-3,Sports,317.02,25,237.76,Credit Card,01-09-2024
3,395d4994,964fc44b-d,Toys,173.19,25,129.89,UPI,01-04-2024
4,a83c145c,d70e2fc6-e,Beauty,244.80,20,195.84,Net Banking,27-09-2024
...,...,...,...,...,...,...,...,...
3655,67abda0a,28714133-6,Beauty,486.79,0,486.79,UPI,14-05-2024
3656,34ebc1a0,08838c2c-9,Toys,212.87,15,180.94,Cash on Delivery,19-11-2024
3657,1defd3b1,c39a4f16-6,Home & Kitchen,389.76,0,389.76,Net Banking,07-08-2024
3658,0611293d,b4f67f96-9,Electronics,447.66,30,313.36,UPI,21-05-2024
3659,e73ad07c,a5d07442-d,Home & Kitchen,235.77,30,165.04,UPI,14-04-2024